<!--
  ~ Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
  ~
  ~ WSO2 Inc. licenses this file to you under the Apache License,
  ~ Version 2.0 (the "License"); you may not use this file except
  ~ in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied. See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->

<!DOCTYPE assembly [
        <!ELEMENT assembly (id|formats|includeBaseDirectory|fileSets|dependencySets|files)*>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT formats (format)*>
        <!ELEMENT format (#PCDATA)>
        <!ELEMENT includeBaseDirectory (#PCDATA)>
        <!ELEMENT fileSets (fileSet)*>
        <!ELEMENT fileSet (directory|outputDirectory|excludes|includes|fileMode|filtered)*>
        <!ELEMENT directory (#PCDATA)>
        <!ELEMENT outputDirectory (#PCDATA)>
        <!ELEMENT excludes (exclude)*>
        <!ELEMENT exclude (#PCDATA)>
        <!ELEMENT includes (include)*>
        <!ELEMENT include (#PCDATA)>
        <!ELEMENT fileMode (#PCDATA)>
        <!ELEMENT filtered (#PCDATA)>
        <!ELEMENT dependencySets (dependencySet)*>
        <!ELEMENT dependencySet (outputDirectory|includes)*>
        <!ELEMENT files (file)*>
        <!ELEMENT file (source|outputDirectory|fileMode|filtered|destName)*>
        <!ELEMENT source (#PCDATA)>
        <!ELEMENT destName (#PCDATA)>
        ]>
<assembly>
    <id>bin</id>
    <formats>
        <format>zip</format>
    </formats>
    <includeBaseDirectory>false</includeBaseDirectory>

    <fileSets>
        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}</outputDirectory>
            <excludes>
                <exclude>**/*.sh</exclude>
                <exclude>**/README*</exclude>
                <exclude>**/LICENSE*</exclude>
                <exclude>**/INSTALL*</exclude>
                <exclude>**/release-notes.html</exclude>
                <exclude>**/axis2services/sample01.aar</exclude>
                <exclude>**/axis2services/echo/**</exclude>
                <exclude>**/axis2services/version/**</exclude>
                <exclude>**/version.txt</exclude>
                <exclude>**/master-datasources.xml</exclude>
                <exclude>**/carbon.xml</exclude>
                <exclude>**/registry.xml</exclude>
                <exclude>**/client-truststore.jks</exclude>
                <exclude>**/wso2carbon.jks</exclude>
                <exclude>**/WSO2AM_DB.h2.db</exclude>
                <exclude>**/WSO2DM_DB.h2.db</exclude>
                <exclude>**/conf/axis2/axis2_client.xml</exclude>
                <exclude>**/conf/axis2/axis2.xml</exclude>
                <exclude>**/conf/etc/launch.ini</exclude>
                <exclude>**/lib/httpmime*</exclude>
                <exclude>**/lib/encoder*</exclude>
                <exclude>**/plugins/jaxb*</exclude>
                <exclude>**/security/authenticators.xml</exclude>
				<exclude>**/user-mgt.xml</exclude>

                <exclude>**/plugins/org.wso2.carbon.localentry.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.mediation.security.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.mediation.library.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.task.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.sequences.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.proxyadmin.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.priority.executors.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.message.store.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.message.processor.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.mediation.templates.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.mediation.artifactuploader.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.endpoint.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.inbound.ui*</exclude>
                <exclude>**/plugins/org.wso2.carbon.rest.api.ui*</exclude>
                <!--excluding asm-all jar after fixing java stack issue-->
                <exclude>**/asm-all_4.1.0.wso2v1.jar</exclude>
                <exclude>**/java-property-utils_1.9.0.wso2v1.jar</exclude>
                <exclude>**/axis2-transport-jms_1.1.0.wso2v13.jar</exclude>
                <exclude>**/axis2-transport-mail_1.1.0.wso2v13.jar</exclude>
                <exclude>**/commons-digester_1.8.1.wso2v1.jar</exclude>
                <exclude>**/org.apache.commons.configuration_1.10.0.jar</exclude>
                <exclude>**/commons-configuration_1.6.0.wso2v1.jar</exclude>
                <exclude>**/net.minidev.json-smart_1.2.0.jar</exclude>
                <exclude>**/libthrift_0.7.0.wso2v2.jar</exclude>
                <exclude>**/com.google.gson_2.3.1.jar</exclude>
                <exclude>**/com.google.gson_2.2.4.jar</exclude>
                <exclude>**/com.google.gson_2.1.0.jar</exclude>
                <exclude>**/com.jayway.jsonpath_0.8.1.wso2v1.jar</exclude>
                <exclude>**/json_1.0.0.wso2v1.jar</exclude>
                <exclude>**/json_2.0.0.wso2v1.jar</exclude>
                <exclude>**/bcprov-jdk15on_1.49.0.wso2v1.jar</exclude>
                <exclude>**/xmlbeans_2.3.0.wso2v1.jar</exclude>
                <exclude>**/nimbus-jose-jwt_2.26.1.wso2v2.jar</exclude>
                <exclude>**/org.wso2.carbon.hostobjects.sso_4.4.3.jar</exclude>
                <exclude>**/org.wso2.carbon.hostobjects.sso_4.3.2.jar</exclude>
                <exclude>**/conf/log4j.properties</exclude>
                <exclude>**/repository/conf/security/Owasp.CsrfGuard.Carbon.properties</exclude>
                <exclude>**/repository/components/plugins/httpclient_4.3.2.wso2v1.jar</exclude>
                <exclude>**/conf/tomcat/carbon/WEB-INF/web.xml</exclude>
            </excludes>
        </fileSet>

        <!-- Copying Runtimes-->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/lib/runtimes
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/lib/runtimes/</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}</outputDirectory>
            <includes>
                <include>**/*.sh</include>
            </includes>
            <excludes>
                <exclude>bin/wso2server.sh</exclude>
                <exclude>bin/wso2server.bat</exclude>
            </excludes>
            <fileMode>755</fileMode>
        </fileSet>

        <!-- Multi-tenancy related file -->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/multitenancy/
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf/multitenancy
            </outputDirectory>
            <includes>
                <include>**/stratos.xml</include>
                <include>**/multitenancy-packages.xml</include>
                <include>**/usage-throttling-agent-config.xml</include>
                <include>**/cloud-services-desc.xml</include>
            </includes>
            <filtered>true</filtered>
        </fileSet>
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/multitenancy/
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf</outputDirectory>
            <includes>
                <include>**/tenant-mgt.xml</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>src/repository/resources/styles/css</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/resources/allthemes/Default/admin
            </outputDirectory>
            <includes>
                <include>**/**.css</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>src/repository/resources/styles/images</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/resources/allthemes/Default/images
            </outputDirectory>
            <includes>
                <include>**/**.gif</include>
                <include>**/**.png</include>
            </includes>
        </fileSet>

        <!-- Copy Documentation -->
        <fileSet>
            <directory>target/site</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/docs</outputDirectory>
            <fileMode>755</fileMode>
        </fileSet>

        <fileSet>
            <directory>../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/modules
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/modules/</outputDirectory>
            <includes>
                <include>**/carbon/</include>
                <include>**/jaggery-test/</include>
                <include>**/process/</include>
                <include>**/uuid/</include>
                <include>**/i18n/</include>
                <include>**/ws/</include>
                <include>**/appmgtpublisher/</include>
                <include>**/appstore/</include>
                <include>**/store/</include>
                <include>**/lifecycle/</include>
                <include>**/utils/</include>
                <include>**/caramel/</include>
                <include>**/markdown/</include>
                <include>**/handlebars/</include>
                <include>**/event/</include>
                <include>**/claims/</include>
                <include>**/permission/</include>
                <include>**/registration/</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>src/repository/conf</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf</outputDirectory>
            <includes>
                <include>**/api-manager.xml</include>
                <include>**/sso-idp-config.xml</include>
                <include>**/application-authentication.xml</include>
                <include>**/log4j.properties</include>
                <include>**/nhttp.properties</include>
                <include>**/passthru-http.properties</include>
				<include>**/user-mgt.xml</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/security
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf/security
            </outputDirectory>
            <includes>
                <include>**/sso-sp-config.properties</include>
                <include>**/entitlement.properties</include>
                <include>**/trusted-idp-config.xml</include>
                <include>**/cipher-text.properties</include>
                <include>**/cipher-tool.properties</include>
            </includes>
            <excludes>
                <exclude>authenticators.xml</exclude>
            </excludes>
        </fileSet>
        <fileSet>
            <directory>src/repository/conf/datasources</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf/datasources
            </outputDirectory>
            <includes>
                <include>**/master-datasources.xml</include>
                <include>**/cdm-datasources.xml</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/datasources
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf/datasources
            </outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/device-types
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf/device-types
            </outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>src/repository/resources</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/resources</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>

        <!--data-bridge configuration-->
        <fileSet>
            <directory>src/repository/conf/data-bridge</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf/data-bridge
            </outputDirectory>
        </fileSet>
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/dbscripts/service-provider
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/dbscripts/service-provider</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>

        <!-- Copying API management related dbscripts -->
        <fileSet>
            <directory>../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/dbscripts/apimgt</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/dbscripts/apimgt</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>
        <!-- Copying APP management related dbscripts -->
        <fileSet>
            <directory>../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/dbscripts/storage</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/dbscripts/storage</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/dbscripts/appmgt</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/dbscripts/appmgt</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>

        <!-- Copying Certificate management related dbscripts -->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/dbscripts/certMgt
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/dbscripts/certMgt</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>
        <!-- Copying Social plugin related dbscripts -->
        <fileSet>
            <directory>../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/dbscripts/social</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/dbscripts/social</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>
        <!-- Copying Social plugin related MSSQL dbscripts from distribution src-->
        <fileSet>
            <directory>src/repository/dbscripts/social</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/dbscripts/social</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>
        <!-- Copying storage related MSSQL dbscripts from distribution src-->
        <fileSet>
            <directory>src/repository/dbscripts/storage</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/dbscripts/storage</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>
        <!--Copying modules-->
        <fileSet>
            <directory>../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/modules</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/modules/</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>src/repository/modules/sso</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/modules/sso</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>
        <!-- This is for APPM -->
        <!-- This has been done to address a flaw in the APPM publisher feature -->
        <fileSet>
            <directory>src/repository/modules/lifecycle</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/modules/lifecycle</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>

        <!--Copying modules-->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/modules
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/modules/</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>src/repository/modules</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/modules</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>

        <!-- Copying Device Management related dbscripts -->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/dbscripts/cdm
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/dbscripts/cdm</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/carbonapps</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/deployment/server/carbonapps
            </outputDirectory>
        </fileSet>
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/resources
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/resources
            </outputDirectory>
        </fileSet>


        <!-- Copying Mobile plugin management related dbscripts -->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.device.mgt.plugin.version}/dbscripts/cdm/plugins
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/dbscripts/cdm/plugins
            </outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
        </fileSet>

        <!-- Copying Authentication Endpoint webapp -->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/webapps
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/deployment/server/webapps
            </outputDirectory>
            <includes>
                <include>authenticationendpoint.war</include>
                <include>oauth2.war</include>
                <include>dynamic-client-web.war</include>
            </includes>
        </fileSet>

		<!-- Copying Authentication Endpoint webapp -->
		<fileSet>
			<directory>
				../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/devicetypes
			</directory>
			<outputDirectory>${pom.artifactId}-${pom.version}/repository/deployment/server/devicetypes
			</outputDirectory>
		</fileSet>

        <!-- Copying mdm app from devicemgt app-->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/jaggeryapps/devicemgt/
            </directory>
            <outputDirectory>
                ${pom.artifactId}-${pom.version}/repository/deployment/server/jaggeryapps/devicemgt
            </outputDirectory>
        </fileSet>
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/jaggeryapps/devicemgt-cdmf/
            </directory>
            <outputDirectory>
                ${pom.artifactId}-${pom.version}/repository/deployment/server/jaggeryapps/devicemgt
            </outputDirectory>
        </fileSet>
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/jaggeryapps/uuf-template-app/
            </directory>
            <outputDirectory>
                ${pom.artifactId}-${pom.version}/repository/deployment/server/jaggeryapps/devicemgt
            </outputDirectory>
        </fileSet>

        <!-- Copying windows-web-agent-->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/jaggeryapps/windows-web-agent/
            </directory>
            <outputDirectory>
                ${pom.artifactId}-${pom.version}/repository/deployment/server/jaggeryapps/windows-web-agent
            </outputDirectory>
			<excludes>
				<exclude>**/jaggery.conf</exclude>
			</excludes>
        </fileSet>
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/jaggeryapps/uuf-template-app/
            </directory>
            <outputDirectory>
                ${pom.artifactId}-${pom.version}/repository/deployment/server/jaggeryapps/windows-web-agent
            </outputDirectory>
        </fileSet>

        <!-- Copying android-web-agent-->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/jaggeryapps/android-web-agent/
            </directory>
            <outputDirectory>
                ${pom.artifactId}-${pom.version}/repository/deployment/server/jaggeryapps/android-web-agent
            </outputDirectory>
			<excludes>
				<exclude>**/jaggery.conf</exclude>
			</excludes>
        </fileSet>
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/jaggeryapps/uuf-template-app/
            </directory>
            <outputDirectory>
                ${pom.artifactId}-${pom.version}/repository/deployment/server/jaggeryapps/android-web-agent
            </outputDirectory>
			<excludes>
				<exclude>**/jaggery.conf</exclude>
			</excludes>
        </fileSet>

        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/webapps/
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/deployment/server/webapps/
            </outputDirectory>
            <excludes>
                <exclude>appmoauth2.war</exclude>
                <exclude>am#sample#calculator#v1.war</exclude>
                <exclude>api.war</exclude>
            </excludes>
            <filtered>false</filtered>
            <fileMode>644</fileMode>
        </fileSet>

        <!-- Copying APP Manager Publisher and Store Jaggery apps -->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/jaggeryapps/publisher/
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/deployment/server/jaggeryapps/publisher
            </outputDirectory>
            <excludes>
                <exclude>publisherLogo/**</exclude>
                <exclude>publisherTheme/**</exclude>
                <exclude>publisherSite/**</exclude>
                <exclude>footer/**</exclude>
                <exclude>localstyles.css</exclude>
				<exclude>**/jaggery.conf</exclude>
            </excludes>
        </fileSet>
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/jaggeryapps/store/
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/deployment/server/jaggeryapps/store
            </outputDirectory>
            <excludes>
                <exclude>storeLogo/**</exclude>
                <exclude>storeSite/**</exclude>
                <exclude>base-page/**</exclude>
                <exclude>login/**</exclude>
                <exclude>styles-layout.css</exclude>
				<exclude>**/jaggery.conf</exclude>
            </excludes>
        </fileSet>

        <!-- Copying API Manager Store Jaggery app -->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/jaggeryapps/api-store/
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/deployment/server/jaggeryapps/api-store
            </outputDirectory>
            <excludes>
                <exclude>storeLogo/**</exclude>
                <exclude>storeSite/**</exclude>
                <exclude>base-page/**</exclude>
                <exclude>login/**</exclude>
                <exclude>styles-layout.css</exclude>
                <exclude>**/site/conf/site.json</exclude>
				<exclude>**/jaggery.conf</exclude>
            </excludes>
        </fileSet>

        <!-- Copying Windows Synapse files -->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/synapse-configs/default/api/
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/deployment/server/synapse-configs/default/api/
            </outputDirectory>
        </fileSet>


        <!--============ Added with API Features ===============-->
        <fileSet>
            <directory>src/api-resources/customsequences</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/resources/customsequences</outputDirectory>
            <includes>
                <include>**/**.xml</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>src/api-resources/default-tiers</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/resources/default-tiers</outputDirectory>
            <includes>
                <include>**/**.xml</include>
            </includes>
        </fileSet>

        <fileSet>
            <directory>../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/deployment/server/jaggeryapps/social/</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/deployment/server/jaggeryapps/social</outputDirectory>
			<excludes>
				<exclude>**/jaggery.conf</exclude>
			</excludes>
        </fileSet>

        <fileSet>
            <directory>src/api-resources/synapse-configs/default/sequences</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/resources/apim-synapse-config/</outputDirectory>
        </fileSet>

        <fileSet>
            <directory>src/api-resources/synapse-configs</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/deployment/server/synapse-configs/</outputDirectory>
        </fileSet>

        <fileSet>
            <directory>src/api-resources/api_templates</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/resources/api_templates</outputDirectory>
            <includes>
                <include>**/**.xml</include>
            </includes>
        </fileSet>

        <!-- Copying RXTs corresponding API management related components -->
        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/rxts
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/resources/rxts
            </outputDirectory>
        </fileSet>

        <fileSet>
            <directory>
                ../p2-profile-gen/target/wso2carbon-core-${carbon.kernel.version}/repository/conf/identity
            </directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/conf/identity
            </outputDirectory>
            <includes>
                <include>**/saml1-assertion-config</include>
                <include>**/msg-mgt.properties</include>
                <include>**/entitlement.properties</include>